### ISSUE TITLE
Unclear error message after upgrading to 0.7

### ISSUE THREAD

**Issue by dvc94ch** [djkoloski/rkyv#175]
```rust
#[derive(Archive, Deserialize, Serialize, Clone, Debug, Eq, PartialEq)]
pub struct Stream {
    pub(crate) head: SignedHead,
    pub(crate) outboard: Vec<u8>,
}

impl Stream {
    pub(crate) fn to_bytes(&self) -> Result<AlignedVec> {
        let mut ser = AlignedSerializer::new(AlignedVec::new());
        ser.serialize_value(self)?;
        Ok(ser.into_inner())
    }
}
```

```
error[E0277]: the trait bound `AlignedSerializer<AlignedVec>: ScratchSpace` is not satisfied
   --> core/src/stream.rs:186:13
    |
186 |         ser.serialize_value(self)?;
    |             ^^^^^^^^^^^^^^^ the trait `ScratchSpace` is not implemented for `AlignedSerializer<AlignedVec>`
    |
    = note: required because of the requirements on the impl of `rkyv::Serialize<AlignedSerializer<AlignedVec>>` for `Vec<u8>`
    = note: 1 redundant requirements hidden
    = note: required because of the requirements on the impl of `rkyv::Serialize<AlignedSerializer<AlignedVec>>` for `stream::Stream`
```

**Comment by djkoloski** [comment]
0.7 added a new `ScratchSpace` trait that allows control over memory allocations during serialization. This allows containers to be serialized in no-std no-alloc environments, and improved performance considerably on the benchmarks. You can use [`AllocSerializer`](https://docs.rs/rkyv/0.7.2/rkyv/ser/serializers/type.AllocSerializer.html) for a good default serializer, or [`CompositeSerializer`](https://docs.rs/rkyv/0.7.2/rkyv/ser/serializers/struct.CompositeSerializer.html) to build your own:

```rust
use rkyv::ser::serializers::AllocSerializer;

// Uses 4096 bytes of heap-allocated scratch space before spilling to globally-allocated memory
let serializer = AllocSerializer::<4096>::default();

// Uses a fixed-size scratch space of 4096 that errors instead of spilling to global memory
use rkyv::{
    ser::serializers::{AlignedSerializer, CompositeSerializer, HeapScratch},
    AlignedVec, Infallible,
};
type MySerializer = CompositeSerializer<AlignedSerializer<AlignedVec>, HeapScratch<4096>, Infallible>;
let serializer = MySerializer::default();
```

This seems like it could be confusing. Any suggestions on how to improve the docs?

**Comment by dvc94ch** [comment]
ah I mixed up `AlignedSerializer` and `AllocSerializer`. Not sure why it requires an `AlignedVec` and a `HeapScratch`, but I'm sure there is a reason.
