### ISSUE TITLE
Doesn't build with rust 1.50.0

### ISSUE THREAD

**Issue by jrmuizel** [djkoloski/rkyv#134]
I get
```
error[E0658]: const generics are unstable
   --> /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv-0.6.4/src/core_impl/mod.rs:406:35
    |
406 | unsafe impl<T: ArchiveCopy, const N: usize> ArchiveCopy for [T; N] {}
    |                                   ^
    |
    = note: see issue #74878 <https://github.com/rust-lang/rust/issues/74878> for more information

error[E0658]: const generics are unstable
   --> /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv-0.6.4/src/core_impl/mod.rs:409:24
    |
409 | impl<T: Archive, const N: usize> Archive for [T; N] {
    |                        ^
    |
    = note: see issue #74878 <https://github.com/rust-lang/rust/issues/74878> for more information

error[E0658]: const generics are unstable
   --> /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv-0.6.4/src/core_impl/mod.rs:431:51
    |
431 | impl<T: Serialize<S>, S: Fallible + ?Sized, const N: usize> Serialize<S> for [T; N] {
    |                                                   ^
    |
    = note: see issue #74878 <https://github.com/rust-lang/rust/issues/74878> for more information

error[E0658]: const generics are unstable
   --> /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv-0.6.4/src/core_impl/mod.rs:446:46
    |
446 | impl<T: Archive, D: Fallible + ?Sized, const N: usize> Deserialize<[T; N], D> for [T::Archived; N]
    |                                              ^
    |
    = note: see issue #74878 <https://github.com/rust-lang/rust/issues/74878> for more information

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `rkyv`
```
when trying to build.

**Comment by djkoloski** [comment]
Since 1.51 enabled support for const generics, the feature has been turned on by default. You can disable const generics for older versions of rust:

```toml
rkyv = { version = "0.6.4", default-features = false, features = ["std"] }
```

**Comment by djkoloski** [comment]
Closing this for now, reopen if this doesn't solve your problem.
